name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile project
        run: |
          cd glados2
          make

      - name: Debug build output
        run: ls -R glados2/

      - name: Create GitHub release and upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: glados2/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
